### ISSUE TITLE
[Question] What is the intention to call getFSRS twice with the first calling always returns null?

### ISSUE THREAD

**Issue by richardoey** [ishiko732/ts-fsrs-demo#19]
Thank you very much for creating this project ! I have interest to create my own flashcard app so I research about FSRS algorithm and found your example is really great! 

I do have a question comes to my mind when I analyze how you update the card schedule. 

```
export async function updateCard(cid:number,now:Date,grade:Grade,duration:number){
    const [_,recordItem]=await Promise.all([getFSRS(cid,true), schedulerCard({cid},now,Number(grade) as Grade)])
```

in your updateCard function, why are there two Promise with almost the same objective? I see schedulerCard() will do the same thing with getFSRS except for returning null. Why do we need to have getFSRS(cid, true) if the return in the end will be null. I don't see the generated user params will be used any where once we give skip=true. 

thank you very much for your time and attention~

**Comment by ishiko732** [comment]
There might be redundant verification here. The `getFSRS(cid, skip=true)` function only contains the authentication information and will skip the retrieval of the FSRS instance. However, the schedulerCard function also calls `getFSRS(cid)` to verify the authentication information and read the FSRS instance. In reality, you only need the `schedulerCard({cid}, now, Number(grade) as Grade)` async function. I will make the modifications later! Thank you!

https://github.com/ishiko732/ts-fsrs-demo/blob/0bef1b610a2c94c1e82f788e21b2df3e2428bd2a/src/lib/fsrs.ts#L114-L126
https://github.com/ishiko732/ts-fsrs-demo/blob/0bef1b610a2c94c1e82f788e21b2df3e2428bd2a/src/lib/card.ts#L53

**Comment by richardoey** [comment]
Thank you very much for your quick response and complete explanation 🙏🙏.
