### ISSUE TITLE
Exercises

### ISSUE THREAD

**Issue by dominikx96** [ishiko732/ts-fsrs-demo#21]
Hi! 

I am building my own anki-like app and your code is very helpful for me to understand how it should work, thank you!
I am planning to add to my app also exercises (for now, simple exercise like "fill the gap").

Swiping cards is my core, but I am trying to figure out how good or bad answer should affect fsrs score and properties. Do you have any suggestions/recommendations?

Thanks!

@ishiko732

**Comment by ishiko732** [comment]
I believe that cards with clearer problem descriptions and shorter answers are easier to remember, which will make the card more deeply imprinted in memory, leading to an FSRS rating tending towards "Easy" (or "Good"). If a card is consistently rated as "Easy", it may not be reviewed for a long period of time, and this is normal. Please do not be surprised by this, as the purpose of FSRS is for long-term learning. For more details on how to create effective cards, you can refer to the 20 rules of formulating knowledge on the SuperMemo website: https://www.supermemo.com/en/blog/twenty-rules-of-formulating-knowledge.
