### ISSUE TITLE
Cannot read properties of undefined (reading 'request_retention')

### ISSUE THREAD

**Issue by astronautfa** [ishiko732/ts-fsrs-demo#7]
I have set up this project but I am getting this error: 
Error: Cannot read properties of undefined (reading 'request_retention') 

from the file : src/lib/fsrs.ts (52:37) @ request_retention

it seems params[0] does not exist on a new database instance

**Comment by ishiko732** [comment]
hello,What database are you using? This demo uses MySQL. Have you configured the DATABASE_URL in the .env.local file? Have you used the command "npm run dbpush"?

```sql
create table Card
(
    cid            int auto_increment primary key,
    due            datetime(3)               default CURRENT_TIMESTAMP(3) not null,
    stability      double                                                 not null,
    difficulty     double                                                 not null,
    elapsed_days   int                                                    not null,
    scheduled_days int                                                    not null,
    reps           int                                                    not null,
    lapses         int                                                    not null,
    state          enum ('0', '1', '2', '3') default '0'                  not null,
    last_review    datetime(3)                                            null,
    nid            int                                                    not null,
    constraint Card_cid_key
        unique (cid),
    constraint Card_nid_key
        unique (nid)
)
    collate = utf8mb4_unicode_ci;

create table Note
(
    nid      int auto_increment
        primary key,
    uid      int                     not null,
    question varchar(191) default '' not null,
    answer   varchar(191) default '' not null,
    source   varchar(191) default '' not null,
    extend   json                    not null,
    sourceId varchar(255)            null,
    constraint Note_nid_key
        unique (nid)
)
    collate = utf8mb4_unicode_ci;

create index Note_uid_idx
    on Note (uid);

create index source__index
    on Note (source, sourceId);

create table Parameters
(
    uid               int auto_increment
        primary key,
    request_retention double     default 0.9   not null,
    maximum_interval  int        default 36500 not null,
    w                 json                     not null,
    enable_fuzz       tinyint(1) default 0     not null,
    card_limit        int        default 50    not null,
    lingq_token       varchar(100)             null,
    lingq_counter     varchar(100)             null,
    constraint Parameters_uid_key
        unique (uid)
)
    collate = utf8mb4_unicode_ci;

create table Revlog
(
    lid               varchar(191)                   not null
        primary key,
    cid               int                            not null,
    grade             enum ('0', '1', '2', '3', '4') not null,
    state             enum ('0', '1', '2', '3')      not null,
    due               datetime(3)                    not null,
    stability         double                         not null,
    difficulty        double                         not null,
    elapsed_days      int                            not null,
    last_elapsed_days int                            not null,
    scheduled_days    int                            not null,
    review            datetime(3)                    not null,
    constraint Revlog_lid_key
        unique (lid)
)
    collate = utf8mb4_unicode_ci;

create index Revlog_cid_idx
    on parallelveil.Revlog (cid);

create table User
(
    uid       int auto_increment
        primary key,
    name      varchar(191)                 not null,
    password  varchar(191)                 not null,
    oauthId   varchar(191)                 not null,
    oauthType varchar(191) default 'local' not null,
    email     varchar(191)                 not null,
    constraint User_email_key
        unique (email),
    constraint User_name_key
        unique (name),
    constraint User_uid_key
        unique (uid)
)
    collate = utf8mb4_unicode_ci;
```

**Comment by ishiko732** [comment]
I need the database information and debug data. Can you provide them?

src/lib/fsrs.ts:
![image](https://github.com/ishiko732/ts-fsrs-demo/assets/62931549/0cbaa94c-cc9b-4197-ada5-30a5dd07c066)

**Comment by astronautfa** [comment]
Yes the local mysql database is in sync with the prisma schema

The console.log(params) debugging showed that params is equal to []

![image](https://github.com/ishiko732/ts-fsrs-demo/assets/145324740/699eaa5f-68b3-4825-9d9b-d012c85700d2)
![image](https://github.com/ishiko732/ts-fsrs-demo/assets/145324740/d68210b5-e54e-49b7-9548-942afea597d8)
![image](https://github.com/ishiko732/ts-fsrs-demo/assets/145324740/0e0bc369-27c9-43aa-84f0-f94592cd9585)

**Comment by ishiko732** [comment]
> Yes the local mysql database is in sync with the prisma schema
> 
> The console.log(params) debugging showed that params is equal to []
> 
> ![image](https://private-user-images.githubusercontent.com/145324740/303944095-699eaa5f-68b3-4825-9d9b-d012c85700d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MTY5NjUsIm5iZiI6MTcwNzcxNjY2NSwicGF0aCI6Ii8xNDUzMjQ3NDAvMzAzOTQ0MDk1LTY5OWVhYTVmLTY4YjMtNDgyNS05ZDliLWQwMTJjODU3MDBkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwNTQ0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzcwZmY4NDA3MmMyZTZhNjM4NGRlMTI4Y2E1NTM5YzBlYTlhOGRhNTc3Y2U5ZDE3NzA1M2M3NjU3MDIzNDAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VHunop5gCKTPE1PebQ9cRIRyWL_32lqwm_c3i2wIxtM) ![image](https://private-user-images.githubusercontent.com/145324740/303943639-d68210b5-e54e-49b7-9548-942afea597d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MTY5NjUsIm5iZiI6MTcwNzcxNjY2NSwicGF0aCI6Ii8xNDUzMjQ3NDAvMzAzOTQzNjM5LWQ2ODIxMGI1LWU1NGUtNDliNy05NTQ4LTk0MmFmZWE1OTdkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwNTQ0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTRlZmFjM2U2ODUwYTNhN2FhOWE4NTRlYWMwM2U5NzdlZjgxMjRhNTExN2JhNmFjNjE4ZjZlNGNkZjg4YTJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q84185o218A2ATn0T2pU0VKlF6j47pAikLIRaDU1en8) ![image](https://private-user-images.githubusercontent.com/145324740/303943923-0e0bc369-27c9-43aa-84f0-f94592cd9585.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MTY5NjUsIm5iZiI6MTcwNzcxNjY2NSwicGF0aCI6Ii8xNDUzMjQ3NDAvMzAzOTQzOTIzLTBlMGJjMzY5LTI3YzktNDNhYS04NGYwLWY5NDU5MmNkOTU4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwNTQ0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGQ1YWRjMzcwNmU4ZDczMDBjMjc2NDJhYjRhZTY4ZTE1YmY0ZWJiNDBjNmQxMDg5OTE2N2JlZDkzNGU3YjMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VkjhVoMJkShVa81PcsyShWsGRTCEfbd2Mji_Ac0yoeI)

You need to check if the corresponding data exists in the `User` and `Parameters` tables. It's possible that it wasn't successfully saved during OAuth login. 

src/lib/fsrs.ts(18:20):
![image](https://github.com/ishiko732/ts-fsrs-demo/assets/62931549/005956f3-6609-4d06-8759-004d4c8b4f95)
![image](https://github.com/ishiko732/ts-fsrs-demo/assets/62931549/8723516c-85d1-43ce-a731-90fb91ed30a6)

I tried modifying the UID to non-existent information, and I was able to reproduce the issue successfully.

**Comment by ishiko732** [comment]
I tried to fix this issue and implemented an automatic logout feature.
![image](https://github.com/ishiko732/ts-fsrs-demo/assets/62931549/d9257483-0bf5-4013-8981-3a3c46e20c61)

**Comment by ishiko732** [comment]
Can you try to fetch that branch and see if it can solve the problem?

```bash
git fetch https://github.com/ishiko732/ts-fsrs-demo Fix/user-not-found-error
git checkout Fix/user-not-found-error
```

**Comment by ishiko732** [comment]
The issue has reappeared in PostgreSQL, and I need to fix it.
